### ISSUE TITLE
AppsActivity crashes on phones with lineageOS installed (and some others)

### ISSUE THREAD

**Issue by UriahShaulMandel** [UriahShaulMandel/BaldPhone#181]
**Describe the bug**
The AppsActivity crashes on phones with lineageOS installed (and some others)

**To Reproduce**
Install lineageOS
Open AppsActivity

**Expected behavior**
To not crash lol - to add the picture to the database successfully

```
java.lang.NullPointerException: Attempt to get length of null array
	at com.bald.uriah.baldphone.utils.S.byteArrayToBitmap(S.java:161)
	at com.bald.uriah.baldphone.databases.apps.AppsDatabaseHelper.loadPic(AppsDatabaseHelper.java:165)
	at com.bald.uriah.baldphone.adapters.AppsRecyclerViewAdapter$AppViewHolder.update(AppsRecyclerViewAdapter.java:184)
	at com.bald.uriah.baldphone.adapters.AppsRecyclerViewAdapter.onBindViewHolder(AppsRecyclerViewAdapter.java:113)
```

Also, quite sure it has something to do with these two:

https://github.com/UriahShaulMandel/BaldPhone/blob/afd53e0d0789a03989c47ae78024208c7272eaf7/app/src/main/java/com/bald/uriah/baldphone/utils/S.java#L160-L162

https://github.com/UriahShaulMandel/BaldPhone/blob/afd53e0d0789a03989c47ae78024208c7272eaf7/app/src/main/java/com/bald/uriah/baldphone/databases/apps/AppsDatabaseHelper.java#L123-L127

**Comment by UriahShaulMandel** [comment]
https://github.com/UriahShaulMandel/BaldPhone/tree/fixing_apps

**Comment by UriahShaulMandel** [comment]
[BALDPHONE_apps_activity_bug_fix.zip](https://github.com/UriahShaulMandel/BaldPhone/files/4020763/BALDPHONE_apps_activity_bug_fix.zip)

**Comment by UriahShaulMandel** [comment]
e2b78f152509d24b01b9f97a86e0b1dc5fc572b3 Should fix it
